a = input('Digite algo: ')
b = a
print('O tipo primitivo desse valor eh {}'.format(b))
print('So tem espaco? ', a.isspace())
print('Eh um numero? ', a.isnumeric())
print('Eh Alfabetico? ', a.isalpha())
print('Eh Alfabumerico? ', a.isalnum())
print('Esta em MAIUSCULAS? ', a.isupper())
print('Esta em minisculas? ', a.islower())
print('Esta capitalizada? ', a.istitle())
print('Esta em ASCII? ', a.isascii())